### PR TITLE
Rails 5 support

### PR DESCRIPTION
**Pull request by DanielHeath**

### CODE REVIEW

**Comment by DanielHeath** [comment]
@devton This should implement everything required. Looks like CI is failing due to using too old a ruby.

**Comment by devton** [comment]
thanks @DanielHeath i'll take a look and make merge if all is good :)

**Comment by DanielHeath** [comment]
Any outstanding issues with this one?

**Comment by DanielHeath** [comment]
Anything still required for this?

**Comment by DanielHeath** [comment]
@devton anything else required for this?

**Comment by devton** [comment]
@DanielHeath sorry i think that already merged :S

**Pull request merged**
